[versions]
minSdk = "33"
targetSdk = "36"
compileSdk = "36"

java = "21"
agp = "9.1.0"
kotlin = "2.3.20"
coreKtx = "1.18.0"
org-jetbrains-coroutines = "1.10.2"

nav3Core = "1.0.1"
coilCompose = "3.4.0"
lifecycleViewmodelNav3 = "2.10.0"
material3AdaptiveNav3 = "1.3.0-alpha09"

#region Test
junit = "4.13.2"
mockk = "1.14.9"
turbine = "1.2.1"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
kotlinx-coroutines-test = "1.11.0"
kover = "0.9.8"
#endregion

#region Bluetooth
nordic-ble = "2.11.0"
nordic-support-ble-scanner = "1.6.0"
nordic-android-common-uiscanner = "1.0.11"
com-polidea-rxandroidble = "1.19.1"
#endregion

#region Security
sqlcipherAndroid = "4.16.0"
#endregion

room = "2.8.4"
navRouter = "1.0.3"
datastore = "1.2.1"
itext7Core = "9.6.0"
healthConnect = "1.1.0"
lottieCompose = "6.7.1"
com-google-ksp = "2.3.6"
androidx-work = "2.11.2"
composeBom = "2026.03.01"
activityCompose = "1.13.0"
kotlinx-datetime = "0.6.2" # Many ext functions for kotlinx.datetime break on version 0.7.1
androidx-hilt-ext = "1.3.0"
com-google-dagger = "2.59.2"
jakewharton-timber = "5.0.1"
lifecycleRuntimeKtx = "2.10.0"
kotlinxSerializationJson = "1.10.0"
org-gradle-android-cache-fix = "3.0.3"
androidx-hilt-navigation-compose = "1.3.0"
androidx-constraintlayout-compose = "1.1.1"
androidx-lifecycle-viewmodel-compose = "2.10.0"

com-github-movisens-smart-gatt = "3.6.0"
io-github-automapper = "0.11.0"
collectionJvm = "1.6.0"

[libraries]
io-github-automapper-processor = { group = "io.github.jacksever.automapper", name = "processor", version.ref = "io-github-automapper" }
io-github-automapper-annotation = { group = "io.github.jacksever.automapper", name = "annotation", version.ref = "io-github-automapper" }

itext7-core = { module = "com.itextpdf.android:itext-core-android", version.ref = "itext7Core" }

io-coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilCompose" }

#region Test
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-test" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
sqlcipher-android = { module = "net.zetetic:sqlcipher-android", version.ref = "sqlcipherAndroid" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
#endregion

#region Android base libraries
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
#endregion

#region Compose libraries
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
#endregion

#region BLE libraries
nordic-ble = { group = "no.nordicsemi.android", name = "ble-common", version.ref = "nordic-ble" }
nordic-ble-ktx = { group = "no.nordicsemi.android", name = "ble-ktx", version.ref = "nordic-ble" }
nordic-support-ble-scanner = { module = "no.nordicsemi.android.support.v18:scanner", version.ref = "nordic-support-ble-scanner" }
nordic-android-common-uiscanner = { module = "no.nordicsemi.android.common:uiscanner", version.ref = "nordic-android-common-uiscanner" }

com-polidea-rxandroidble = { module = "com.polidea.rxandroidble2:rxandroidble", version.ref = "com-polidea-rxandroidble" }
#endregion

androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }

androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3Core" }
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3Core" }
androidx-lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycleViewmodelNav3" }
androidx-material3-adaptive-navigation3 = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation3", version.ref = "material3AdaptiveNav3" }

androidx-datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "datastore" }
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "androidx-work" }
androidx-health-connect-client = { module = "androidx.health.connect:connect-client", version.ref = "healthConnect" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }

navigation-router = { module = "io.github.arttttt.nav3router:nav3router", version.ref = "navRouter" }

androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "androidx-constraintlayout-compose" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle-viewmodel-compose" }

jakewharton-timber = { module = "com.jakewharton.timber:timber", version.ref = "jakewharton-timber" }

kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "org-jetbrains-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "org-jetbrains-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

com-github-movisens-smart-gatt = { module = "com.github.movisens:SmartGattLib", version.ref = "com-github-movisens-smart-gatt" }

lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottieCompose" }

google-dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "com-google-dagger" }
androidx-hilt-ext-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "androidx-hilt-ext" }
androidx-hilt-ext-common = { group = "androidx.hilt", name = "hilt-common", version.ref = "androidx-hilt-ext" }
androidx-hilt-ext-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "androidx-hilt-ext" }
androidx-collection-jvm = { group = "androidx.collection", name = "collection-jvm", version.ref = "collectionJvm" }
google-dagger-hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "com-google-dagger" } # instrumentation testing
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidx-hilt-navigation-compose" }

dagger-hilt-core = { module = "com.google.dagger:hilt-core", version.ref = "com-google-dagger" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "com-google-dagger" }

#region Gradle plugins
gradlePlugin-android = { module = "com.android.tools.build:gradle", version.ref = "agp" }
gradlePlugin-room = { group = "androidx.room", name = "room-gradle-plugin", version.ref = "room" }
gradlePlugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradlePlugin-compose = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
gradlePlugin-hilt = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "com-google-dagger" }
gradlePlugin-kover = { module = "org.jetbrains.kotlinx.kover:org.jetbrains.kotlinx.kover.gradle.plugin", version.ref = "kover" }
gradlePlugin-ksp = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "com-google-ksp" }
gradlePlugin-cache-fix = { group = "org.gradle.android.cache-fix", name = "org.gradle.android.cache-fix.gradle.plugin", version.ref = "org-gradle-android-cache-fix" }
gradlePlugin-kotlin-serialization = { module = "org.jetbrains.kotlin.plugin.serialization:org.jetbrains.kotlin.plugin.serialization.gradle.plugin", version.ref = "kotlin" }
#endregion

[bundles]
health-stream-test = ["junit", "kotlinx-coroutines-test", "mockk", "turbine"]
health-stream-ble = ["nordic-ble", "nordic-ble-ktx", "nordic-support-ble-scanner", "nordic-android-common-uiscanner", "com-polidea-rxandroidble"]
health-stream-compose = ["androidx-compose-material3", "androidx-compose-ui", "androidx-compose-runtime", "androidx-compose-ui-tooling-preview", "androidx-constraintlayout-compose", "androidx-activity-compose", "androidx-lifecycle-viewmodel-compose"]

[plugins]
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
